development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: apotomo_development
  pool: 5
  username: root
  password: p@ssw0rd123

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: apotomo_test
  pool: 5
  username: root
  password: p@ssw0rd123
  reconnect: true

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: apotomo_production
  pool: 5
  username: root
  password:

